name: test

on:
  push:

jobs:
  test:
    strategy:
        matrix:
          go-version: [1.21.x, 1.22.x]
          os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps: 
    - name: Install Go
      uses: actions/setup-go@v2.1.3
      with:
        go-version: ${{ matrix.go-version }}
    - name: Checkout
      uses: actions/checkout@v2
    - name: Test
      run: go test -race -v ./... -coverprofile=.cover.out && go tool cover -func=.cover.out
